# Generated by Django 5.2 on 2025-04-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flow', models.CharField(blank=True, max_length=100)),
                ('wa_id', models.CharField(max_length=17, unique=True)),
                ('wa_name', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('peti_id', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('payment_option', models.CharField(blank=True, max_length=100)),
                ('ordered_product_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_id', models.CharField(blank=True, max_length=100)),
                ('curr', models.CharField(blank=True, max_length=100)),
                ('item_price', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('wa_id', models.CharField(max_length=18)),
                ('msg_id', models.CharField(max_length=110, unique=True)),
                ('msg', models.TextField(default='')),
                ('interactive_id', models.CharField(default='', max_length=150)),
                ('interactive_desc', models.CharField(default='', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(default='', max_length=30)),
                ('media_id', models.CharField(default='', max_length=60)),
                ('img_path', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Peti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(blank=True, max_length=100)),
                ('seller_phone', models.CharField(blank=True, max_length=100)),
                ('cod_status', models.BooleanField(default=True)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('payment_option', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.BooleanField(blank=True, default=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.products')),
            ],
        ),
    ]
