# Generated by Django 3.2 on 2023-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_staff'),
        ('chatbot', '0003_alter_products_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_admin_id', to='dashboard.customuser'),
        ),
    ]
