# Generated by Django 3.2 on 2023-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_sellers_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
