# Generated by Django 3.2 on 2023-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
    ]
