# Generated by Django 3.2 on 2023-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_orders_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='staff',
        ),
        migrations.AddField(
            model_name='orders',
            name='dispatch',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='sellers',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellers',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
