# Generated by Django 3.2 on 2023-04-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20230419_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
